import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SessionWrapper from "@/components/SessionWrapper";
import { auth } from "@/lib/auth";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const session = await auth();
  return (
    <>
      <html lang="en">
        <body className={`${inter.className} bg-gray-100 min-h-screen`}>
          <div className="container mx-auto p-4">
            <SessionWrapper session={session}>{children}</SessionWrapper>
          </div>
        </body>
      </html>
    </>
  );
}

export default RootLayout
